import type { SkillGroup } from "./types"

export const skills: SkillGroup[] = [
  {
    id: "agentic",
    label: "Agentic AI & LLM",
    skills: [
      "LangGraph",
      "LangChain",
      "Model Context Protocol",
      "Multi-agent systems",
      "Tool / function calling",
      "Model routing",
      "Prompt engineering",
      "Context engineering",
      "LLM output evaluation",
      "Re-rankers",
      "n8n",
    ],
  },
  {
    id: "rag",
    label: "RAG, Vector DBs & Providers",
    skills: [
      "RAG",
      "Pinecone",
      "Chroma",
      "FAISS",
      "Cognee Knowledge Graph",
      "Embeddings",
      "Retrieval pipeline design",
      "OpenAI API",
      "Google Gemini API",
      "Meta Llama",
      "Hugging Face",
    ],
  },
  {
    id: "backend",
    label: "Languages & Backend",
    skills: ["Python", "FastAPI", "Flask", "Django", "REST APIs", "GraphQL", "JavaScript / Node.js", "Java"],
  },
  {
    id: "cloud",
    label: "Cloud, DevOps & Distributed Systems",
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "GitHub Actions",
      "Terraform",
      "Async workers",
      "Redis queues",
      "Rate limiting",
      "Retries",
      "Load balancing",
      "Observability",
    ],
  },
  {
    id: "data",
    label: "Data & ML",
    skills: [
      "PyTorch",
      "TensorFlow",
      "NLP",
      "Neural networks",
      "Computer vision",
      "Data preprocessing",
      "PostgreSQL",
      "MongoDB",
      "Redis",
    ],
  },
]
